### ISSUE TITLE
undefined is not an object (evaluating '_react.PropTypes.number') 

### ISSUE THREAD

**Issue by naxir** [akilb/rukatuk-mobile#14]
I was facing this problem i.e undefined is not an object (evaluating '_react.PropTypes.number') 
and i have solved this with below mentioned Steps
1)npm i prop-types -S
2)Go to modules direcorty and search react-native-smart-badge
3) Inside this module open Badge.js
4) Instead of importing 'prop-types' from react import it from 'prop-types' i.e 
**import PropTypes from 'prop-types';**

Well i have fixed this problem the other audience who are getting this problem follow above steps thanks

**Comment by akilb** [comment]
@naxir thanks for sharing a workaround!
